name: Docker build a PR

on:
  push:
    branches:
    - '!main'
  pull_request:
    branches:
    - '**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: docker build and push, kubectl apply
        run: |
          docker build -t levelupdevops-pr:${{ github.sha }} .
